
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 18;
  public static final int POW = 45;
  public static final int CHAR = 2;
  public static final int GE = 54;
  public static final int TCHAR = 10;
  public static final int TRATIONAL = 9;
  public static final int TFLOAT = 8;
  public static final int INTEGER = 6;
  public static final int SEMI = 63;
  public static final int LPAREN = 56;
  public static final int FOR = 33;
  public static final int RPAREN = 59;
  public static final int LCURL = 58;
  public static final int AND = 47;
  public static final int NOT = 46;
  public static final int LT = 51;
  public static final int RANGE = 19;
  public static final int RATIONAL = 4;
  public static final int ILLEGAL_CHARACTER = 65;
  public static final int OR = 48;
  public static final int IN = 36;
  public static final int TDEF = 29;
  public static final int COMMA = 64;
  public static final int TBOOL = 12;
  public static final int DIV = 44;
  public static final int THREAD = 20;
  public static final int ASSIGN = 40;
  public static final int IF = 37;
  public static final int MAIN = 31;
  public static final int DOT = 32;
  public static final int LE = 52;
  public static final int WAIT = 25;
  public static final int OF = 34;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int MUL = 43;
  public static final int ADD = 41;
  public static final int TSTR = 11;
  public static final int BREAK = 15;
  public static final int FDEF = 28;
  public static final int CONTAINS = 55;
  public static final int VOID = 14;
  public static final int EQ = 49;
  public static final int TOP = 16;
  public static final int RCURL = 61;
  public static final int COLON = 62;
  public static final int TINT = 7;
  public static final int ELSE = 39;
  public static final int DICT = 17;
  public static final int READ = 22;
  public static final int LSQBKT = 57;
  public static final int WHILE = 35;
  public static final int FLOAT = 3;
  public static final int RSQBKT = 60;
  public static final int LEN = 24;
  public static final int STRING = 5;
  public static final int ALIAS = 30;
  public static final int FALSE = 27;
  public static final int GT = 53;
  public static final int SUB = 42;
  public static final int ELIF = 38;
  public static final int PRINT = 21;
  public static final int NOTEQ = 50;
  public static final int IDENTIFIER = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CHAR",
  "FLOAT",
  "RATIONAL",
  "STRING",
  "INTEGER",
  "TINT",
  "TFLOAT",
  "TRATIONAL",
  "TCHAR",
  "TSTR",
  "TBOOL",
  "IDENTIFIER",
  "VOID",
  "BREAK",
  "TOP",
  "DICT",
  "SEQ",
  "RANGE",
  "THREAD",
  "PRINT",
  "READ",
  "RETURN",
  "LEN",
  "WAIT",
  "TRUE",
  "FALSE",
  "FDEF",
  "TDEF",
  "ALIAS",
  "MAIN",
  "DOT",
  "FOR",
  "OF",
  "WHILE",
  "IN",
  "IF",
  "ELIF",
  "ELSE",
  "ASSIGN",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "POW",
  "NOT",
  "AND",
  "OR",
  "EQ",
  "NOTEQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "CONTAINS",
  "LPAREN",
  "LSQBKT",
  "LCURL",
  "RPAREN",
  "RSQBKT",
  "RCURL",
  "COLON",
  "SEMI",
  "COMMA",
  "ILLEGAL_CHARACTER"
  };
}

